# Generated by Django 4.2.28 on 2026-02-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='goodie_collected',
            new_name='midnight_snacks',
        ),
        migrations.AddField(
            model_name='participant',
            name='breakfast_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='dinner_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='lunch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='midnight_snacks_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='registration_goodies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='registration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='snacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='snacks_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='uid',
            field=models.CharField(db_index=True, help_text='NFC tag hardware UID in uppercase hex without colons', max_length=32, unique=True),
        ),
    ]
