# Generated by Django 5.2.9 on 2026-02-28 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_team_participant_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisteredMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('is_linked', models.BooleanField(default=False, help_text='True once an NFC UID has been assigned to this slot.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_registered', to='events.team')),
            ],
            options={
                'verbose_name': 'Pre-Registered Member',
                'verbose_name_plural': 'Pre-Registered Members',
                'ordering': ['name'],
                'unique_together': {('team', 'name')},
            },
        ),
    ]
